### ISSUE TITLE
The latest update breaks anyenv

### ISSUE THREAD

**Issue by jomo666** [anyenv/anyenv#70]
The latest update breaks anyenv installation. My `anyenv` is installed into specific directory, defined by the `ANYENV_ROOT` environment variable, e.g. using the old init

````
git clone https://github.com/riywo/anyenv /somedir/anyenv
````

and my `.profile` is

````
export ANYENV_ROOT=/somedir/anyenv
export PATH="$ANYENV_ROOT/bin:$PATH"
eval "$(anyenv init -)"
````

The above always worked flawlessly.

Now, it prints error message:

> ANYENV_DEFINITION_ROOT(/Users/username/.config/anyenv/anyenv-install) doesn't exist. You can initialize it by:
> anyenv install --init

so, clearly **do not** honors the `ANYENV_ROOT` variable, and incorrectly trying to find the `anyenv` in the `$HOME`.

The current method allows only two places
- `${XDG_CONFIG_HOME}/anyenv/anyenv-install` and
- `${HOME}/.config/anyenv/anyenv-install`)

The question is:

- how to install the `anyenv` into arbitrary directory, like `/some/anyenv`, where the `/some` is definitely **not** my `XDG_CONFIG_HOME`.

Please also consider: The `XDG_CONFIG_HOME` and like may be applied within  desktop software applications, such in specific desktop environments –  (KDE, GNOME) or other desktop environments on X.org platforms. But the `anyenv` has nothing with the **freedesktop.org** project. E.g. relying on the `freedesktop.org` specification is not fully OK, because for example here are other systems also which doesn't uses the `XDG` specs... (like `macOS`).

Is possible continue to honor the `ANYENV_ROOT` variable?

(Also, sorry for my terrible english).

**Comment by jomo666** [comment]
So, started again from "zero" - and tried the following:

```
git clone https://github.com/anyenv/anyenv /opt/anyenv
```

added into my `.profile`

```
export ANYENV_DEFINITION_ROOT=/opt/anyenv
export PATH="$ANYENV_DEFINITION_ROOT/bin:$PATH"
eval "$(anyenv init -)"
```

after opening a new terminal window it prints

> grep: /opt/anyenv/*env: No such file or directory

when tried to install list the availavle envs,

`anyenv install -l` prints again the same line and nothing more.

the command `anyenv install plenv` prints

> $ anyenv install plenv
> anyenv-install: definition not found: plenv

so, it looks like still buggy a bit. I was a wonderful piece of software - great work - I hope that the it will be again :)

Ps: the github doesn't allows reopen issue when the maintainer closed it... so i could post a new issue which will be a bit contra-productive. :(

**Comment by jomo666** [comment]
If it doesn’t work, please reopen this issue.


By the github rules, I cannot re-open my own issues if a repo collaborator
closed them. So... It is still buggy, added the comment - but can't reopen
it.

thank you.
jm

**Comment by MetricMike** [comment]
You'll need to set both vars like so:
```
export ANYENV_ROOT=/opt/anyenv
export ANYENV_DEFINITION_ROOT="${ANYENV_ROOT}/anyenv-install
export PATH="${ANYENV_ROOT}/bin:${PATH}"
```

Both vars are independent of each other (see: https://github.com/anyenv/anyenv/blob/master/libexec/anyenv-install) and do not reference each other by default, so you'll have to explicitly set both.

**Comment by jomo666** [comment]
@MetricMike thank you, tried your example, but still doesn't works. But no problem - just forked this repo and rolled back the last 7 commits - and got the good-old working solution. :) Hopefully once it will works again. :D Thank you.

**Comment by tabulon** [comment]
Hi @MetricMike, 

Thank you for `anyenv`. It's a great idea.

**EDIT**: To my embrassement, I can **no longer reproduce** this issue. 

I don't really know what was initially wrong, but after wiping the whole ` anyenv` tree, starting the install/setup from scratch with a few restarts of iTerm in between ==> so far, **everything appears to work as expected/advertised!** 😅  

Thanks again and my apologies for the false alarm. 

I am leaving my original post below intact. If anything, it could help someone who might stumble upon this later. 🤣 

------

I can confirm that this issue still exists as of the latest  `anyenv` version (`1.1.4`), even following the exact  recipie you have given above on Feb 5 2019, i.e.:

```bash
export ANYENV_ROOT=/opt/anyenv
export ANYENV_DEFINITION_ROOT="${ANYENV_ROOT}/anyenv-install
export PATH="${ANYENV_ROOT}/bin:${PATH}"

eval "$(anyenv init -)"
```
This results in the below output message from `anyenv` :
*(the output has been intentionally obscured, by replacing my username with `$USERNAME$`).*

```
ANYENV_DEFINITION_ROOT(/Users/$USERNAME$/.config/anyenv/anyenv-install) doesn't exist. You can initialize it by:
> anyenv install --init
```
  (`~/.anyenv/` appears to be automatically set up as a symlink to `~/.config/anyenv/` by the way)

- I have also tried *pre-creating* the `anyenv-install` under the desired location (just to see if it makes a difference) ==> **Nope**, same result.

- Then tried running `anyenv install --init` anyways  ==> **No luck** 
  *it  just went ahead and populated the  `anyenv-install` directory below my `$HOME` (`.config/anyenv/anyenv-install`).*

- Just to see what happens next, I went ahead and installed plenv with `anyenv install plenv` ==> **No luck**. 
  `plenv` got installed under  `~/.config/anyenv/envs/plenv`

- As a last ditch try:  I installed `plenv` again after (after uninstalling the `plenv` installed by the above step), with the command below:
  ```ANYENV_ENVS_ROOT=/opt/anyenv/envs      anyenv install plenv```

   ==> **No luck**, either.  It just installed under `~/.config/anyenv/envs/plenv` just like when launched without setting `ANYENV_ENVS_ROOT`.

At this point, I gave up trying anything else.

Therefore, setting `ANYENV_DEFINITION_ROOT` or even also `ANYENV_ENVS_ROOT` (in addition to  `ANYENV_ROOT`) does not appear to have any effect whatsoever ==> It is effectively ignored by `anyenv`. 

Just in case you may request it, I am jotting down the specifics of my environment down below, but I doubt they are at all relevant.

Probably, this is one of those workflows that doesn't get tested/reported very often because most users probably go with the default locations (for both `ANYENV_ROOT` and `ANYENV_DEFINITION_ROOT`).

It would be great if it actually _did_ work, though.  Some operating systems (such as `macOS`, but also `centos`) are notorious for having insanely old system binaries for most scripting interpreters and shells (when they are actually there)...

# RATIONALE / USE-CASE

If all one needs is just one (and only one) up-to-date version of an interpreter or shell to be able to run scripts system-wide, there is `homebrew` (for macOS)... That's what I use for `bash` as well as many other things.

If one also needs to tweak/develop/test stuff on some *env, then `homebrew` won't cut it, promting you to go with an `*env` solution... 

BUT, if you still need the ability run a stable version (of perl, python, ...) with a bunch of modules as your daily horse system-wide, then you would NOT want to have your *env under your `$HOME` (at least for some `su` tasks...)

In that case, you basically do need to install `*env` under some available system-wide directory, such as  `/opt` or `/user/local/site/`  (`/usr/local/` itself is basically monopolized by `homebrew` on macOS).

### System/Environment DETAILS:

I am running **macOS Catalina** (Version 10.15.7), with the below  :

```bash 
 # outputs are represented with a ':==>'  prefix

anyenv --version 
:==> anyenv 1.1.4'

bash    --version
:==> GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin19.6.0)
```
