### ISSUE TITLE
'anyenv install' issue under osx

### ISSUE THREAD

**Issue by spinscale** [anyenv/anyenv#74]
I installed anyenv via brew. I had to create the `/Users/$USER/.anyenv/envs/`  directory manually in order to run `anyenv install crenv`. 

I ran ` anyenv install --update` before that. Maybe I was missing a step. If so, feel free to close.

**Comment by riywo** [comment]
Do you see any error message which could help me to understand the root cause?

**Comment by spinscale** [comment]
```
# anyenv install crenv

/var/folders/xx/111r6kc974z_tmqc70rymxkm0000gn/T/crenv.20190509102530.22909 ~/devel/elastic/elasticsearch/elasticsearch
Cloning https://github.com/pine/crenv.git master to crenv...
Cloning into 'crenv'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 578 (delta 0), reused 0 (delta 0), pack-reused 577
Receiving objects: 100% (578/578), 119.09 KiB | 677.00 KiB/s, done.
Resolving deltas: 100% (334/334), done.
~/devel/elastic/elasticsearch/elasticsearch
mv: rename /var/folders/xx/111r6kc974z_tmqc70rymxkm0000gn/T/crenv.20190509102530.22909/crenv to /Users/alr/.anyenv/envs/crenv: No such file or directory
```

`/Users/alr/.anyenv/envs` is the missing directory. after adding it manually everything works.

**Comment by xinii** [comment]
I have a similar problem, but it is not exactly the same.

I am not a new installation, I found I can't use `python` (via `pyenv` via `anyenv`), but after I re-installed a different `python` version using `pyenv` (via `anyenv`), I find the new version of python appeared by
`pyenv versions` (which means I can use the new version of python)
I noticed this installation is automatically installed to `~/.pyenv/versions` instead of `~/.anyenv/envs/pyenv/versions`, and `nodenv`, `rbenv` are the same situation, so I moved the python versions in envs `~/.anyenv/envs/pyenv/versions` of anyenv to `.pyenv/versions`, and everythins seems okay. However, when executes python on the terminal , it seems to load the python version on `~/.anyenv/envs/pyenv/versions`, so I created a hyperlink from `.pyenv/versions` to `~/.anyenv/envs/pyenv/versions`, and the problem solved temporary.
This problem seems to have some relevance to the above problem.
Here just for test, if I move `~/.pyenv` to some other name like `aaa`, and run `anyenv update`, will output like this:
```
Updating 'anyenv'...
Updating 'anyenv/anyenv-git'...
Updating 'anyenv/anyenv-update'...
Skipping 'nodenv'; not git repo
/Users/xin/.anyenv/plugins/anyenv-update/bin/anyenv-update: 221 行: cd: /Users/xin/.pyenv: No such file or directory
```

**Comment by riywo** [comment]
Thanks, I quickly updated and sent PR to Homebrew for version up. See progress here https://github.com/Homebrew/homebrew-core/pull/40841

**Comment by riywo** [comment]
It has been shipped. Please update your Homebrew and see it is working.

**Comment by spinscale** [comment]
works now. thx for fixing!
